name: Setup and Run OwnCloud Temporarily

on:
  push:
    branches:
      - main

jobs:
  setup-owncloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update package list and install necessary packages
      run: |
        sudo apt-get update
        sudo apt-get install -y apache2 postgresql postgresql-contrib php libapache2-mod-php php-pgsql php-json php-mbstring php-curl php-xml php-pear php-bcmath php-zip php-intl php-gd unzip wget

    - name: Start PostgreSQL service
      run: |
        sudo systemctl start postgresql
        sudo systemctl enable postgresql

    - name: Set up PostgreSQL database and user
      run: |
        sudo -i -u postgres psql -c "CREATE USER ownclouduser WITH PASSWORD 'owncloud';"
        sudo -i -u postgres psql -c "CREATE DATABASE ownclouddb OWNER ownclouduser;"

    - name: Download and unzip OwnCloud
      run: |
        wget https://download.owncloud.com/server/stable/owncloud-complete-latest.zip
        sudo unzip owncloud-complete-latest.zip -d /var/www/

    - name: Set permissions
      run: |
        sudo mkdir -p /var/www/owncloud/data
        sudo chown -R www-data:www-data /var/www/owncloud/

    - name: Set up Apache configuration for OwnCloud
      run: |
        echo '<VirtualHost *:80>
          ServerAdmin webmaster@localhost
          DocumentRoot /var/www/owncloud

          <Directory /var/www/owncloud/>
            Options +FollowSymlinks
            AllowOverride All

            <IfModule mod_dav.c>
              Dav off
            </IfModule>

            SetEnv HOME /var/www/owncloud
            SetEnv HTTP_HOME /var/www/owncloud

          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined

        </VirtualHost>' | sudo tee /etc/apache2/sites-available/owncloud.conf

    - name: Enable OwnCloud site and restart Apache
      run: |
        sudo a2ensite owncloud.conf
        sudo systemctl restart apache2

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin

    - name: Start ngrok
      run: |
        nohup ngrok http 80 &
        sleep 10
        curl -s localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

    - name: Keep the job running for testing
      run: sleep 1h
